### ISSUE TITLE
How can we support multiple "users" in a larger account?

### ISSUE THREAD

**Issue by rreinhardt9** [lessonly/demux#22]
We currently allow you to "connect" an app to an account via the account_id field. For example, you may have a "company" that contains many users and the "company" may be your "account" in Demux.

In the above scenario, what if you have an app that can be activated on a user by user basis and not just on a company basis? If the connections are just on the company level, we do not know which users have installed the app and are forced to send signals for any user that triggers one in that company... even if only 1 user has installed the app and all the other users are irrelevant. We would waste a lot of time and resources sending signals for all those other users that are not relevant for this integration.

On the other side, some integrations want to know about ALL events in the account/company (the app is essentially installed at the company level).

Is there a way that we can better handle this situation?

## Use case: Bulk Action

One potential use case that I've started to see is when a bulk action happens that impacts many users (let's say 30,000) and we want to send a signal for the thing that happened in that bulk action for those users. Let's say we have 3 apps named A, B, and C that are subscribed to the bulk assignment signal.

App A want's to know of any and all assignments, but apps b and c are only concerned with the 3 or 4 users that have installed them per company (low usage).

One thought is that we could create connections to more than one account type... so in the case of app A we would connect to the "company" as before and receive notifications for all users, where as for app B, and C we would create a connection to individual "user" records. For each user in the bulk action we would trigger a signal to notify of an assignment being made. App A would receive all the notifications, but for app B and C we would need to demux each individual user notification to see which apps are listening for that specific user (if any).

This means that if we trigger a bulk action for 30,000 users with 3 apps subscribed to that action, we will end up triggering 30,000 demuxing jobs. Each of those jobs will attempt to resolve the apps that are listening for each user and then queue another job for them. That means that, each one of those 30,000 demuxing jobs would then trigger at least 1 (maybe up to 3) other jobs to handle sending the notification to the apps listening for that user/signal. The more apps listening, the higher that multiplication of jobs after demuxing.

While this works in theory, I'm concerned that maybe connecting directly to user accounts won't scale for bulk actions like we hoped in this case and bulk actions will need special handling.

Signals should be sent quickly, so in order for them to scale during bulk actions in the app a better pattern might be to only send some kind of unique identifier in the signal that represents the bulk event. The apps will then receive this signal and then use the unique ID to retrieve relevant specifics via an API on demand. This way, the signals will always take the same amount of time whether your bulk action includes 3 records or 300,000+.

## Use Case: Don't send one off signals for users that have not installed the app.

For example, let's say your "account" is a "shop" and you have "shoppers" in that shop. Those shoppers can install special integrations to enhance their shopping experience in your store.

In this case, it would be a waste for us to send a "shopper added item to cart" signal to an installed partner app for all shoppers if only 1 has installed the integration and is the only one that is relevant.

In this use case, if we allowed installing multiple "account" types, some apps could install on the "shop" if they are interested in the activity of all users while others could install specifically on the "shopper" records.

Now, when a shopper adds an item to the cart we will first see if an app is listening either for the shop or for the shopper before we send the signal.

In the case of our integration installed by only 1 shopper, the demuxer would still run each time a user added an item to their cart but it would only resolve to our app and send a signal if the shopper that did so is the 1 that installed the integration. All of the activity from other shoppers is ignored (for this specific app, of course it might resolve to others).

Between the two possible use cases, this one actually seems to make the most sense as a reason to install by user account.

**Comment by joshmfrankel** [comment]
For these use cases I considered the following changes:

* Add `account_type` as an optional argument for Demux::Signal
* Add `account` as an optional argument for passing a full object to a Signal
* Modify `account_id` to be optional
* New handling of account vs account_id/account_type - You either need an account object or a combination of id and type
* Resolving the Demuxer continues to work the same with the addition of an account_type argument. Behind the scenes passing a fully qualified object via `account` just pulls off the class as a string
* SignalAttributes gains the account_type argument for #initialize and #from_object (this ensures that Transmissions are now unique on both account_id and account_type; A possibility to consider if we have different object types sending signals with the same account_id)
* Several minor Demux::Transmission additions for account_type (most importantly #attributes_required_to_transmit_present?)
* Demux::App needs to be able to accept account_type
* DB migration for new column

For our tests

* I changed company_id on the Lesson signal to account_id. Hoping to keep this more generic in case others utilize the gem and add to the test suite. This requires some model changes and db changes
* Added a few associations to the dummy models as well as supporting fixtures

All in all I didn't run into any specific roadblocks following this pattern. I added the account or account_id/account_type params option above to preserve the current behavior which relies on account_id. This also gives a shortcut to just passing in a object instead of specifying two arguments (if consumers want to)

**Comment by rreinhardt9** [comment]
That is so helpful, that's for that technical dive @joshmfrankel !!!

One thing that is occurring to me is that a benefit in our "bulk action" use case might be in being able to retrieve which users are installed on a specific app. So for example, if you wanted to get all of the "tasks" that were assigned to all users that have installed a particular app via a graphQL API, you might have a query like:

```
{
  app {
      tasksFromBulkAssignment(id!) {
    }
  }
}
```
And it would return only task assignments from the bulk assignment with that ID for users that have installed that app 🤔 So it could be that even though in the bulk action use case installing on a user wouldn't be use when demuxing, it could be used when retrieving data view the API?

**Comment by rreinhardt9** [comment]
@joshmfrankel I had some more specific thought on implementation...

There may be cases where multiple account types are interested in the same general event. In the "shopper" example above, it could be that we want partner apps to be able to both be connected to individual "shoppers", or to have the option to connect to the whole "shop" and receive notifications anytime ANY shopper adds something to their cart. I've been struggling with how to handle this.

### Accept Multiple Account Types
For one thing, do we accept MULTIPLE account types in one signal? Maybe something like `CartSignal.new(3, accounts: [{ account_id: 3, account_type: :shop }, { account_id: 34, account_type: :shopper }]).item_added`

#### Upsides to this approach:
- We can still call one signal
- When demuxing, we can would only transmit once to that app even if multiple account types resolve

#### Downsides:
- It's super verbose
- Now we have the complexity of possibly needing to handle an array of accounts
- In the signals, you would never be confident what type of account you are dealing with. Right now you have access to `account_id`, but which account are we talking about now? Would this need to change to contain the more complex accounts array object?

### Make Signals Account Type Specific
Another option would be if we decided that signals can only be create for a specific account type. In this scenario, if something happened that you wanted to notify both the "shopper" accounts and the "shop" account, you would have two signals and call them both like:
```Ruby
Shopper::CartSignal.new(3, account_id: 34).item_added
Shop::CartSignal.new(3, account_id: 3).item_added
```
They would both resolve on their own with their respective account types. In the signal, maybe we could allow you to specify the account type the signal is for:
```Ruby
# Shopper::CartSignal
attributes object_class: Cart, signal_name: "shopper_cart_signal", account_type: Shopper

# Shop::CartSignal
attributes object_class: Cart, signal_name: "shop_cart_signal", account_type: Shop
```

#### Upsides:
- This avoids the complexity of having to accept some complex data structure representing multiple accounts
- You can be confident in the signal what type of account we are resolving for
- It will work well with the existing way signals work... there isn't going to need to be a large change to how we work with "Signal Attributes" and the like (just have to add "account_type" to it like we talked about before).
- Subscribing to the signals by name still works with the "array" of names that we have already. So if an app is interested in "shop" level cart signals, it can subscribe to it by name using "shop_cart_signal"

#### Downsides:
- You have to trigger more than one signals in instances where we might have an interest at multiple account levels


### Should Demux::Apps Only Install On One Account Type?
One last thought; I'm wondering if it would be best to lean into making a Demux::App choose one type of account to install on? In the example above, Demux::Apps would be forced to choose between installing at the "Shopper" level or the "Shop" level, but you would not be both. I'm not sure what the answer is there; I can't think of any use cases right now where installing an multiple account types makes sense and it would help keep things clear to only allow installing on one type at a time 🤔

**Comment by rreinhardt9** [comment]
IF we make signals account specific, I think one thing that could help us is to make the attributes that are set inheritable (similar to how sidekiq_options were made inheritable in [this commit](https://github.com/mperham/sidekiq/commit/0addaba4a6162e397743ea60400e35b40d548f40)).

I'm thinking, we can use Rails `class_attributes` directly like in this diff:

```Ruby
# lib/demux/signal.rb:9 
  class Signal
    attr_reader :account_id, :context

    class_attribute :attributes_hash, :object_class, :signal_name
 
    class << self

      def attributes(attr)
        self.attributes_hash = (attributes_hash || {}).merge(attr)
        self.object_class = attributes_hash.fetch(:object_class)
        self.signal_name = attributes_hash.fetch(:signal_name)
      end
    end
```

What this would allow users of the library to do would be use base cases of signals to avoid having to set shared attributes (like account_type) for every signal.

For example, if your app uses only one account_type, you could create a `ApplicationSignal` base class that sets account_type and everything inherits from.

If your app uses multiple account types, you could have a `UserSignal` and a `CompanySignal` base class that signals of those types would inherit from and that would set the account_type for that class of signal.

The problem I'm pondering here is that if we make signals account type specific, I didn't want to create a situation where we start to get a lot of boilerplate that has to be set on each signal.

An alternative would be to have a "default account type" set in the initializer and then we just override on a case by case basis. I'm not sure I like that alternative as much because it makes the account type remote from where we are working with it in the signals and it also doesn't help with having to explicitly specify any non default account type on those signals. It's making the assumption that there is a "primary" account type that is "default", but at least in the use case we are looking at right now they will probably be used pretty equally?
